### ISSUE TITLE
Delete variable not working?

### ISSUE THREAD

**Issue by muthomas** [naofireblade/homebridge-logic#7]
Using Eve app, I select Remove Variable. Then at Name, I enter the name of an existing variable. Then select "On" on the next line. But the variable persists.

**Comment by naofireblade** [comment]
I just tested this with the most recent eve app and it's still working for me. Please watch out for these 2 pitfalls:
- hit return after entering the variable name and before hitting the On button
- check the "my variables" device 2 or 3 times because eve might need these refreshes to update the list
